version: '3.11.8'
services:
  web:
    image: konrad09/dsc_analyzer:latest
    ports:
      - "8000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ./<your_data_folder>:/app/data