version: '3.11.8'
services:
  DSC_Analyzer:   # Dienstname
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ./<your_data_folder>:/app/data
      - ./<your_instance_folder>:/app/instance